version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yii2-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - yii-net

  nginx:
    image: nginx:stable
    container_name: yii2-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - yii-net

  db:
    image: mysql:5.7
    container_name: yii2-db
    restart: always
    environment:
      MYSQL_DATABASE: yii2basic
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yii2pass
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - yii-net

networks:
  yii-net:

volumes:
  dbdata:
