services:
  app:
    image: ubaidullah244/yii2-app:latest
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"
    networks:
      - yii-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      - yii-net

networks:
  yii-net:
