version: '3'

services:
  yii2-app:
    build: .
    container_name: yii2-app
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

