server {
    listen 80;
    server_name yii2-dev.duckdns.org;  # or your EC2 public IP

    root /app/web;  # Update this if you're mounting the app differently
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;  # talking to FPM inside Docker
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /app/web$fastcgi_script_name;
    }
}
