name: Run Ansible Playbook on EC2

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo (to get the Dockerfile)
        uses: actions/checkout@v3

      - name: Clone yii2-app-basic repo
        run: |
          git clone https://github.com/yiisoft/yii2-app-basic.git yii2-app
          cp Dockerfile yii2-app/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./yii2-app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest
          
  deploy_application_on_EC2:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python and Ansible
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install ansible

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Create dynamic inventory
        run: |
          mkdir -p inventory
          echo "[ec2]" > inventory/hosts.ini
          echo "${{ secrets.EC2_HOST }} ansible_user=${{ secrets.EC2_USER }}" >> inventory/hosts.ini

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory/hosts.ini Ansible/playbook.yml

      
